# Generated by Django 5.0.4 on 2024-04-15 17:37
from random import randint

import django.db.models.deletion
from django.db import migrations, models

from hackernews.models import HackerNews, Comments

from faker import Faker
import requests
import json


def seed_comments(hacker_story):
    fake = Faker()

    for _1 in range(randint(3, 13)):
        comment_level_1 = Comments.objects.create(
            hacker_new=hacker_story,
            content=fake.text(),
        )
        for _2 in range(randint(0, 7)):
            comment_level_2 = Comments.objects.create(
                hacker_new=hacker_story,
                content=fake.text(),
                parent=comment_level_1
            )
            for _3 in range(randint(0, 3)):
                Comments.objects.create(
                    hacker_new=hacker_story,
                    content=fake.text(),
                    parent=comment_level_2
                )


def seed_hackernews(apps, schema_editor):
    res = requests.get('https://hacker-news.firebaseio.com/v0/newstories.json')
    stories_ids = json.loads(res.text)
    for story_id in stories_ids:
        try:
            res = requests.get(f'https://hacker-news.firebaseio.com/v0/item/{story_id}.json')
            story = json.loads(res.text)
            hacker_story = HackerNews.objects.create(
                title=story['title'],
                author=story['by'],
                content=story['url'],
                rating=story['score']
            )
            seed_comments(hacker_story)
        except Exception as e:
            print(e)


# def fill_comments(apps, schema_editor):
#     hacker_news = HackerNews.objects.all()


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name='HackerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                             related_name='replies', to='hackernews.comments')),
                ('hacker_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                                 to='hackernews.hackernews')),
            ],
        ),
        migrations.RunPython(seed_hackernews)
    ]
