# Generated by Django 5.0.4 on 2024-04-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_comments_is_parent_alter_comments_hacker_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_parent',
        ),
    ]
